# ============================================================
# BUTLER'S SYMMETRY-BASED KOLMOGOROV-SMIRNOV TEST
# (Fisherian randomization inference for matched-pair /
#  stratified randomized experiments)
# ============================================================

# Internal: Butler's one-sample symmetry statistic for a vector of
# within-pair differences d. D = max_t | F(t) + F(-t-) - 1 |, where
# F is the ECDF of d and F(-t-) is its left-hand limit at -t.
.kk_butler_D <- function(d) {
  pts <- sort(unique(c(d, -d)))
  Ft <- vapply(pts, function(t) mean(d <= t), numeric(1)) # F(t)
  Fnt <- vapply(pts, function(t) mean(d < -t), numeric(1)) # F(-t-)
  max(abs(Ft + Fnt - 1))
}

# Internal: weighted stratified two-sample statistic
# D = max_y | sum_k pi_k { F_[k]1(y) - F_[k]0(y) } |.
.kk_butler_strat_D <- function(y, trt, str, pts) {
  n <- length(y)
  g <- numeric(length(pts))
  for (idx in split(seq_len(n), str)) {
    tk <- trt[idx]
    y1 <- y[idx][tk == 1L]
    y0 <- y[idx][tk == 0L]
    if (length(y1) == 0 || length(y0) == 0) next
    pik <- length(idx) / n
    F1 <- vapply(pts, function(v) mean(y1 <= v), numeric(1))
    F0 <- vapply(pts, function(v) mean(y0 <= v), numeric(1))
    g <- g + pik * (F1 - F0)
  }
  max(abs(g))
}

#' Butler's Symmetry-Based Kolmogorov-Smirnov Test (KK)
#'
#' @description Fisherian randomization test of the sharp null hypothesis of no
#'   treatment effect in matched-pair or stratified randomized experiments,
#'   using Butler's symmetry-based Kolmogorov-Smirnov-type statistic. Unlike the
#'   naive two-sample KS test it respects the pairing / stratification, and
#'   unlike the Wilcoxon signed-rank test it retains power against highly
#'   asymmetric or heavy-tailed effect distributions. The reference distribution
#'   is built by sign-flipping (matched pairs) or within-stratum label
#'   permutation, giving an exact Monte-Carlo p-value.
#'
#'   Two interfaces are provided:
#'   * **Matched pairs** - pass `x` as a numeric vector of within-pair
#'     differences (treated - control). The statistic tests symmetry about zero
#'     and the null distribution is generated by random sign flips.
#'   * **Stratified** - pass `x` as a data frame together with `outcome`,
#'     `treatment`, and `strata` columns. The weighted stratified statistic is
#'     used and treatment labels are permuted within strata.
#'
#' @param x A numeric vector of within-pair differences, or a data frame for the
#'   stratified interface.
#' @param outcome,treatment,strata Column names (bare or string) for the
#'   stratified interface. `treatment` must have exactly two levels; it is
#'   coerced so the second level (or `1`/`TRUE`) is the treated group.
#' @param n_sim Number of Monte-Carlo randomizations (default 9999).
#' @param seed Optional integer seed for reproducibility.
#'
#' @return One-row tibble with the observed statistic `D`, the Monte-Carlo
#'   `p.value`, the `method`, the sample size, and `n_sim`. The full null
#'   distribution is attached as the attribute `null_distribution`.
#'
#' @examples
#' # Matched-pair differences (treated - control)
#' set.seed(1)
#' diffs <- rnorm(40, mean = 0.6)
#' kk_butler_ks(diffs, n_sim = 999)
#'
#' # Stratified randomized experiment
#' df <- data.frame(
#'   y = c(rnorm(50, 1), rnorm(50, 0), rnorm(40, 2), rnorm(40, 1)),
#'   trt = rep(c(1, 0, 1, 0), times = c(50, 50, 40, 40)),
#'   block = rep(c("A", "B"), times = c(100, 80))
#' )
#' kk_butler_ks(df, outcome = y, treatment = trt, strata = block, n_sim = 999)
#'
#' @export
kk_butler_ks <- function(x, outcome = NULL, treatment = NULL, strata = NULL,
                         n_sim = 9999, seed = NULL) {
  if (!is.null(seed)) set.seed(seed)

  # ---- Matched-pair (vector of differences) interface ----
  if (is.numeric(x) && is.null(dim(x))) {
    d <- x[!is.na(x)]
    n <- length(d)
    if (n < 3) stop("Need at least 3 non-missing differences.")

    d_obs <- .kk_butler_D(d)
    absd <- abs(d)
    d_null <- vapply(seq_len(n_sim), function(m) {
      .kk_butler_D(absd * sample(c(-1, 1), n, replace = TRUE))
    }, numeric(1))

    p <- (1 + sum(d_null >= d_obs)) / (n_sim + 1)
    out <- tibble::tibble(
      D = d_obs, p.value = p,
      method = "Butler matched-pair symmetry KS test",
      n = n, n_sim = n_sim
    )
    attr(out, "null_distribution") <- d_null
    return(out)
  }

  # ---- Stratified data-frame interface ----
  if (!inherits(x, "data.frame")) {
    stop("`x` must be a numeric vector of differences or a data frame.")
  }
  data <- x
  y_name <- .kk_colname(rlang::enquo(outcome))
  t_name <- .kk_colname(rlang::enquo(treatment))
  s_quo <- rlang::enquo(strata)
  s_name <- if (rlang::quo_is_null(s_quo)) NULL else .kk_colname(s_quo)

  need <- c(y_name, t_name, s_name)
  missing_cols <- setdiff(need, names(data))
  if (length(missing_cols) > 0) {
    stop("Column(s) not found in data: ", paste(missing_cols, collapse = ", "))
  }

  keep <- stats::complete.cases(data[, need, drop = FALSE])
  data <- data[keep, , drop = FALSE]
  y <- data[[y_name]]
  trt_raw <- data[[t_name]]
  # Coerce treatment to 0/1 (second level / TRUE / 1 = treated)
  if (is.logical(trt_raw)) {
    trt <- as.integer(trt_raw)
  } else {
    lv <- sort(unique(trt_raw))
    if (length(lv) != 2) stop("`treatment` must have exactly two levels.")
    trt <- as.integer(trt_raw == lv[2])
  }
  str <- if (is.null(s_name)) rep(1L, length(y)) else as.integer(factor(data[[s_name]]))

  n <- length(y)
  if (n < 4) stop("Need at least 4 complete observations.")
  pts <- sort(unique(y))

  d_obs <- .kk_butler_strat_D(y, trt, str, pts)

  # Permute treatment labels within strata
  strata_idx <- split(seq_len(n), str)
  d_null <- vapply(seq_len(n_sim), function(m) {
    trt_perm <- trt
    for (idx in strata_idx) trt_perm[idx] <- trt[sample(idx)]
    .kk_butler_strat_D(y, trt_perm, str, pts)
  }, numeric(1))

  p <- (1 + sum(d_null >= d_obs)) / (n_sim + 1)
  method <- if (is.null(s_name)) {
    "Butler two-sample symmetry KS test"
  } else {
    "Butler stratified symmetry KS test"
  }
  out <- tibble::tibble(
    D = d_obs, p.value = p, method = method,
    n = n, n_sim = n_sim
  )
  attr(out, "null_distribution") <- d_null
  out
}
